mib/forms/__init__.py
from .login import LoginForm
from .user import UserForm

all_forms = [LoginForm, UserForm]

mib/forms/login.py
import wtforms as f
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """Form created to allow users to login
    """

    email = f.StringField(
        'Email',
        validators=[DataRequired()],
        id="inputEmail",
    )
    password = f.PasswordField('Password', validators=[DataRequired()])
    display = ['email', 'password']

mib/forms/user.py
import wtforms as f
from flask_wtf import FlaskForm
from wtforms.fields.html5 import DateField, EmailField, TelField
from wtforms.validators import DataRequired, Email

from mib.validators.age import AgeValidator


class UserForm(FlaskForm):
    """Form created to allow the customers sign up to the application.
    This form requires all the personal information, in order to create the account.
    """

    email = EmailField(
        'Email',
        validators=[DataRequired(), Email()]
    )

    firstname = f.StringField(
        'Firstname',
        validators=[DataRequired()]
    )

    lastname = f.StringField(
        'Lastname',
        validators=[DataRequired()]
    )

    password = f.PasswordField(
        'Password',
        validators=[DataRequired()]
    )

    birthdate = DateField(
        'Birthday',
        validators=[AgeValidator(min_age=18)]
    )

    phone = TelField(
        'Phone',
        validators=[DataRequired()]
    )

    display = ['email', 'firstname', 'lastname', 'password',
               'birthdate', 'phone']

mib/__init__.py
import os

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_environments import Environments

__version__ = '0.1'

login = None
debug_toolbar = None
app = None


def create_app():
    """
    This method create the Flask application.
    :return: Flask App Object
    """
    global app
    global login

    app = Flask(__name__, instance_relative_config=True)

    flask_env = os.getenv('FLASK_ENV', 'None')
    if flask_env == 'development':
        config_object = 'config.DevConfig'
    elif flask_env == 'testing':
        config_object = 'config.TestConfig'
    elif flask_env == 'production':
        config_object = 'config.ProdConfig'
    else:
        raise RuntimeError(
            "%s is not recognized as valid app environment. You have to setup the environment!" % flask_env)

    # Load config
    env = Environments(app)
    env.from_object(config_object)

    register_extensions(app)
    register_blueprints(app)
    register_handlers(app)

    # loading login manager
    import mib.auth.login_manager as lm
    login = lm.init_login_manager(app)

    if flask_env == 'testing' or flask_env == 'development':
        register_test_blueprints(app)

    return app


def register_extensions(app):
    """
    It register all extensions
    :param app: Flask Application Object
    :return: None
    """
    global debug_toolbar

    if app.debug:
        try:
            from flask_debugtoolbar import DebugToolbarExtension
            debug_toolbar = DebugToolbarExtension(app)
        except ImportError:
            pass

    # adding bootstrap
    Bootstrap(app)


def register_blueprints(app):
    """
    This function registers all views in the flask application
    :param app: Flask Application Object
    :return: None
    """
    from mib.views import blueprints
    for bp in blueprints:
        app.register_blueprint(bp, url_prefix='/')


def register_test_blueprints(app):
    """
    This function registers the blueprints used only for testing purposes
    :param app: Flask Application Object
    :return: None
    """

    from mib.views.utils import utils
    app.register_blueprint(utils)


def register_handlers(app):
    """
    This function registers all handlers to application
    :param app: application object
    :return: None
    """
    from .handlers import page_404, error_500

    app.register_error_handler(404, page_404)
    app.register_error_handler(500, error_500)

mib/rao/__init__.py
"""
This package contains all objects
that has the responsibility for accessing
to resources.
RAO is the acronym of Resource Access Object.
"""

mib/views/__init__.py
from .auth import auth
from .home import home
from .users import users

"""List of the views to be visible through the project
"""
blueprints = [home, auth, users]

mib/views/auth.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import login_required, login_user, logout_user
from mib.forms import LoginForm
from mib.rao.user_manager import UserManager

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login(re=False):
    """Allows the user to log into the system

    Args:
        re (bool, optional): boolean value that describes whenever
        the user's session is new or needs to be reloaded. Defaults to False.

    Returns:
        Redirects the view to the personal page of the user
    """
    form = LoginForm()

    if form.is_submitted():
        email, password = form.data['email'], form.data['password']
        user = UserManager.authenticate_user(email, password)
        if user is None:
            # user is not authenticated
            flash('Invalid credentials')
        else:
            # user is authenticated
            login_user(user)
            return redirect(url_for('home.index'))

    return render_template('login.html', form=form, re_login=re)


@auth.route('/relogin')
def re_login():
    """Method that is being called after the user's session is expired.

    """
    return login(re=True)


@auth.route('/logout')
@login_required
def logout():
    """This method allows the users to log out of the system

    Returns:
        Redirects the view to the home page
    """
    logout_user()
    return redirect(url_for('home.index'))

mib/views/home.py
from flask import Blueprint, render_template

home = Blueprint('home', __name__)


@home.route('/', methods=['GET', 'POST'])
def index():
    """General route for the index page
    """
    return render_template("index.html")

mib/views/users.py
from flask import Blueprint, redirect, render_template, url_for, flash
from flask_login import (login_user, login_required)

from mib.forms import UserForm
from mib.rao.user_manager import UserManager
from mib.auth.user import User

users = Blueprint('users', __name__)


@users.route('/create_user/', methods=['GET', 'POST'])
def create_user():
    """This method allows the creation of a new user into the database

    Returns:
        Redirects the user into his profile page, once he's logged in
    """
    form = UserForm()

    if form.is_submitted():
        email = form.data['email']
        password = form.data['password']
        firstname = form.data['firstname']
        lastname = form.data['lastname']
        birthdate = form.data['birthdate']
        date = birthdate.strftime('%Y-%m-%d')
        phone = form.data['phone']
        response = UserManager.create_user(
            email,
            password,
            firstname,
            lastname,
            date,
            phone
        )

        if response.status_code == 201:
            # in this case the request is ok!
            user = response.json()
            to_login = User.build_from_json(user["user"])
            login_user(to_login)
            return redirect(url_for('home.index', id=to_login.id))
        elif response.status_code == 200:
            # user already exists
            flash('User already exists!')
            return render_template('create_user.html', form=form)
        else:
            flash('Unexpected response from users microservice!')
            return render_template('create_user.html', form=form)
    else:
        for fieldName, errorMessages in form.errors.items():
            for errorMessage in errorMessages:
                flash('The field %s is incorrect: %s' % (fieldName, errorMessage))

    return render_template('create_user.html', form=form)


@users.route('/delete_user/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_user(id):
    """Deletes the data of the user from the database.

    Args:
        id_ (int): takes the unique id as a parameter

    Returns:
        Redirects the view to the home page
    """

    response = UserManager.delete_user(id)
    if response.status_code != 202:
        flash("Error while deleting the user")
        return redirect(url_for('auth.profile', id=id))
        
    return redirect(url_for('home.index'))

mib/views/utils.py
from flask import Blueprint, abort

# this is only a utility view
utils = Blueprint('util', __name__)


@utils.route('/server_error')
def generate_server_error():
    """
    This method will generate an error
    :return: Error 500
    """
    return abort(500)

mib/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Message in a Bottle - {% block title %}{% endblock %}</title>

    {% block head %}
    {% endblock %}
</head>

<body>

{% block navbar %}
     {% if current_user.is_authenticated %}
        {% include "components/navbar/user_navbar.html" %}
    {% else %}
        {% include "components/navbar/anonymous_navbar.html" %}
    {% endif %}
{% endblock %}

<main role="main" class="container">
    {% block flashing_messages %}
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="row">
                    <div class="col-md-12">
                        <ul class="flashes">
                            {% for message in messages %}
                                <div class="alert alert-warning">
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
        {% endwith %}
    {% endblock %}

    {% block content %}
    {% endblock %}
</main>

{% block scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

{% endblock scripts %}
{% block footer %}
    <footer class="footer">
        <div class="container">
            <span class="text-muted">Message in a Bottle &copy;</span>
        </div>
    </footer>
{% endblock %}
</body>
</html>

mib/templates/components/navbar/anonymous_navbar.html
{% extends "components/navbar/base_navbar.html" %}
{% block navbar_links %}{# no content #}{% endblock %}
{% block navbar_profile_links %}
    <div class="btn-group">
        <a class="btn btn-info" href="{{ url_for('auth.login') }}">Login</a>
        <a class="btn btn-success" href="{{ url_for('users.create_user') }}">Sign Up</a>
    </div>
{% endblock %}

mib/templates/components/navbar/base_navbar.html
{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
        <a class="navbar-brand" href="/">Message in a Bottle</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse right" id="navbarCollapse">
            {% block navbar_links %}
            {% endblock %}
        </div>
        <div class="collapse navbar-collapse right" id="navbarCollapse">
            <form class="form-inline mt-3 mt-md-0" method="GET" action="/search">
                <input class="form-control mr-sm-2" type="text" name="keyword" placeholder="Search" aria-label="Search">
                <select class="form-control mr-sm-2" name="filters">
                    <option>Name</option>
                    <option>City</option>
                    <option>Menu Type</option>
                </select>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        <div>
            {% block navbar_profile_links %}
                <a href="">Profile</a>
            {% endblock %}
        </div>
    </nav>
{% endblock %}

mib/templates/components/navbar/user_navbar.html
{% extends "components/navbar/base_navbar.html" %}

{% block navbar_links %}

{% endblock %}
{% block navbar_profile_links %}

{% endblock %}

mib/templates/create_user.html
{% extends "base.html" %}
{% from 'bootstrap/wtf.html' import form_field %}

{% block title %} Sign up {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="display-4">Sign up</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {{ form.hidden_tag() }}

                {% for field in form.display %}
                    {{ form_field(form[field]) }}
                {% endfor %}
                <input type=submit value="Signup" class="btn btn-primary">
            </form>
        </div>
    </div>


{% endblock %}

{% block footer %}
{% endblock %}

mib/templates/index.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Message in a Bottle</h1>
        <p class="lead">
            Lorem ipsum!
        </p>
        <hr class="my-4">
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

mib/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block head %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block flashing_messages %}
{% endblock %}
{% block content %}
    <form class="form-signin" action="" method="POST">
        {{ form.hidden_tag() }}
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required
               autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <a class="btn btn-lg btn-secondary btn-block" 
                href="{{ url_for('home.index') }}">Go back</a>
        {% if re_login %}
            <br/>
            <div class="alert alert-warning" role="alert">
                Your session is expired, please login again.
            </div>
        {% endif %}
    </form>
{% endblock %}

{% block footer %}
{% endblock %}

mib/templates/users.html
{% extends "base.html" %}

{% block title %} Users {% endblock %}

{% block content %}
    <h1>User List</h1>
    <ul>
        {% for user in users%}
            <li>
                {{ user.firstname }} {{ user.lastname }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

{% block footer %}
{% endblock %}